### ISSUE TITLE
2017/10/12以降のnightlyパッケージが作られていない

### ISSUE THREAD

**Issue by cosmo0920** [groonga/packages.groonga.org#5]
http://packages.groonga.org/nightly/ にて2017/10/12以降のnightlyパッケージが作られていません。
Cc: @kenhys

**Comment by kenhys** [comment]
I'll check it. Thank you for reporting!

**Comment by kenhys** [comment]
This commit breaks it.
https://github.com/groonga/groonga/commit/dd156c48d00c8d9a78117a370b3e592822c2b95b

**Comment by kenhys** [comment]
maybe fixed.

**Comment by kenhys** [comment]
2017.10.20.tar.gz was generated. 
As "close" button" is not displayed, could you close this issue?

**Comment by cosmo0920** [comment]
I've confirmed that this issue has been fixed. Closing.
